### PR TITLE
Update LibPack to Qt6/Py3.12/OCCT7.8 and migrate script to Python 3 (and to this repo)

### PR DESCRIPTION
**Pull request by chennes**
The actual generation of the LibPack used to be based elsewhere, and was a CLBundler script based on Python 2.7. This is a ground-up rewrite of the LibPack generation system, and a very large upgrade to the current LibPack itself.

### CODE REVIEW

**Comment by chennes** [comment]
This PR could use some people to try to compile it on various systems. Obviously it works on our CI systems, but I'd like to make sure that it doesn't break anyone else's Qt6 setup.

**Comment by chennes** [comment]
Even with the fix to Boost when compiling with the latest MSVC, I still get a return code of 1 (but no reported error) -- everything seems to have worked, and the header files get installed, which is what the script looks for to see if Boost has been done. I could add code that actively rolls back that installation if the return code isn't zero.

**Comment by shaise** [comment]
Update!!
The issue again is the new MSVC.
with the following patch from: ifilippov-pgi at https://github.com/boostorg/boost/issues/914
compilation of boost succeeded!
At first it did not work, but you need to clean up the cloned boost folder from all non git files. (or remove the folder and re-clone it)
shai

**Comment by shaise** [comment]
Ok, the entire libpack built without any issues.
CMake also worked correctly
However when compiling freecad I get a lot of
`Error	LNK2001	unresolved external symbol __imp__Py_NegativeRefcount`
and some other similar py-refcount symbols.
Using your freecad fork, branch: updateForLibPack3
Thanks!
shai

**Comment by shaise** [comment]
Another update!!
Turns out I was compiling debug mode, when I turned to release mode, the compilation was flawless apart from 'missing OS_M_PI symbol' at assembly. Dont know what was the issue - perhaps some include loop. I copied the define manually to assembly and it compiled correct.
Finally have QT6 on windows, Thanks!
```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37848 (Git)
Build type: Release
Branch: updateForLibPack3
Hash: 8c5c9e4359029cc43a8116fe5b61d5bbc44edf90
Python 3.12.3, Qt 6.7.1, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.0
Locale: English/United States (en_US)
Installed mods: 
  * BIM_Workbench 2021.12.0
  * fasteners 0.5.24
  * Manipulator 1.5.7
  * OpenTheme 2024.5.16
  * PieMenu 1.5.1
  * Render 2024.1.23
  * SelectorToolbar
  * sheetmetal 0.4.18
  * TabBar (Disabled)
```

**Comment by chennes** [comment]
I've added a patch for Boost 1.85 to allow it to compile with MSVC 14.4. The last thing to work on is a bit of code to clean up the resulting cMake files and remove their references to the local build system.

**Comment by chennes** [comment]
I plan to merge this after https://github.com/FreeCAD/FreeCAD/pull/10337 is in, then create a new beta release of the LibPack for use in the latest development builds of FreeCAD.
